#FROM python:latest

#ADD requirements.txt /py/
#ADD queries.py /py/
#ADD dm_queries.py /py/
#ADD get_space_data.py /py/
#ADD custom.py /py/
#ADD run_me.py /py/

#RUN python3 -m venv /opt/venv
#COPY requirements.txt .
#RUN . /opt/venv/bin/activate | pip install -r ./py/requirements.txt
#RUN . /opt/venv/bin/activate | pip install psycopg2

#WORKDIR /py/